package com.stu.spring.SpringBootCore_Bean;


//ApplicationConfig 创建CustomBean...
//CustomBean构造方法执行...
//CustomBean @PostConstruct 初始化方法执行...
//CustomBean InitializingBean#afterPropertiesSet 执行...
//CustomBean 自定义init方法执行...
//Started AppSpringBootApplication in 0.401 seconds (JVM running for 0.623)
//监听到 ApplicationStartedEvent - Spring Boot启动完成...
//Spring Boot应用启动完成！
//CustomBean @PreDestroy 销毁方法执行...
//CustomBean DisposableBean#destroy 执行...
//CustomBean 自定义destroy方法执行...