spring:
  application:
    name: rpc-client # 客户端应用名称
  profiles:
    active: dev

rpc:
  etcd:
    host: localhost # etcd 主机
    port: 2379      # etcd 端口
    timeout: 5000   # 连接 etcd 的超时时间（毫秒）
    namespace: /rpc/services # 与服务端一致的命名空间

logging:
  level:
#    org.springframework: info
    com.web.rpc: info