spring:
  application:
    name: rpc-client # 客户端应用名称
  profiles:
    active: dev

logging:
  level:
    #    org.springframework: info
    com.web.rpc: DEBUG         # 调试 RPC 相关日志
    io.netty: INFO             # Netty日志级别