// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_message.proto

package com.web.rpc.core.protocol.proto;

public final class RpcMessage {
  private RpcMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_web_rpc_core_protocol_RpcRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_web_rpc_core_protocol_RpcRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_web_rpc_core_protocol_RpcRequestProto_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_web_rpc_core_protocol_RpcRequestProto_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_web_rpc_core_protocol_RpcResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_web_rpc_core_protocol_RpcResponseProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_web_rpc_core_protocol_RpcMessageProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_web_rpc_core_protocol_RpcMessageProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021rpc_message.proto\022\031com.web.rpc.core.pr" +
      "otocol\"\323\002\n\017RpcRequestProto\022\022\n\nrequest_id" +
      "\030\001 \001(\t\022\024\n\014service_name\030\002 \001(\t\022\023\n\013method_n" +
      "ame\030\003 \001(\t\022\r\n\005group\030\004 \001(\t\022\017\n\007version\030\005 \001(" +
      "\t\022H\n\007headers\030\006 \003(\01327.com.web.rpc.core.pr" +
      "otocol.RpcRequestProto.HeadersEntry\022\030\n\020p" +
      "arameter_values\030\007 \003(\014\022\027\n\017parameter_types" +
      "\030\010 \003(\t\022\020\n\010trace_id\030\t \001(\t\022\021\n\ttimestamp\030\n " +
      "\001(\003\022\017\n\007one_way\030\013 \001(\010\032.\n\014HeadersEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\214\001\n\020RpcResp" +
      "onseProto\022\022\n\nrequest_id\030\001 \001(\t\022\023\n\013status_" +
      "code\030\002 \001(\005\022\016\n\006result\030\003 \001(\014\022\025\n\rerror_mess" +
      "age\030\004 \001(\t\022\025\n\rerror_details\030\005 \001(\014\022\021\n\ttime" +
      "stamp\030\006 \001(\003\"\246\001\n\017RpcMessageProto\022\024\n\014magic" +
      "_number\030\001 \001(\005\022\017\n\007version\030\002 \001(\005\022\024\n\014messag" +
      "e_type\030\003 \001(\005\022\032\n\022serialization_type\030\004 \001(\005" +
      "\022\030\n\020compression_type\030\005 \001(\005\022\022\n\nrequest_id" +
      "\030\006 \001(\003\022\014\n\004data\030\007 \001(\014B#\n\037com.web.rpc.core" +
      ".protocol.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_web_rpc_core_protocol_RpcRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_web_rpc_core_protocol_RpcRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_web_rpc_core_protocol_RpcRequestProto_descriptor,
        new java.lang.String[] { "RequestId", "ServiceName", "MethodName", "Group", "Version", "Headers", "ParameterValues", "ParameterTypes", "TraceId", "Timestamp", "OneWay", });
    internal_static_com_web_rpc_core_protocol_RpcRequestProto_HeadersEntry_descriptor =
      internal_static_com_web_rpc_core_protocol_RpcRequestProto_descriptor.getNestedTypes().get(0);
    internal_static_com_web_rpc_core_protocol_RpcRequestProto_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_web_rpc_core_protocol_RpcRequestProto_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_web_rpc_core_protocol_RpcResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_web_rpc_core_protocol_RpcResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_web_rpc_core_protocol_RpcResponseProto_descriptor,
        new java.lang.String[] { "RequestId", "StatusCode", "Result", "ErrorMessage", "ErrorDetails", "Timestamp", });
    internal_static_com_web_rpc_core_protocol_RpcMessageProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_web_rpc_core_protocol_RpcMessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_web_rpc_core_protocol_RpcMessageProto_descriptor,
        new java.lang.String[] { "MagicNumber", "Version", "MessageType", "SerializationType", "CompressionType", "RequestId", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
